services:
  # Frontend Web Service (Angular + Nginx)
  - type: web
    name: insurance-frontend
    env: docker
    region: oregon
    plan: starter
    branch: main
    dockerfilePath: frontend/Dockerfile
    dockerContext: frontend
    healthCheckPath: /health

  # Backend API Service (Node/Express)
  - type: web
    name: insurance-backend
    env: docker
    region: oregon
    plan: starter
    branch: main
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    healthCheckPath: /api/v1/admin/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

